
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/gamepad/gamepad_standard_mappings.h

package org.chromium.content.browser.input;

public class CanonicalAxisIndex {
  public static final int LEFT_STICK_X = 0;
  public static final int LEFT_STICK_Y = 1;
  public static final int RIGHT_STICK_X = 2;
  public static final int RIGHT_STICK_Y = 3;
  public static final int COUNT = 4;
}
