
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/interfaces/audio_output_stream.mojom
//

package org.chromium.media.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public interface AudioOutputStreamProvider extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends AudioOutputStreamProvider, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<AudioOutputStreamProvider, AudioOutputStreamProvider.Proxy> MANAGER = AudioOutputStreamProvider_Internal.MANAGER;


    void acquire(
org.chromium.mojo.bindings.InterfaceRequest<AudioOutputStream> outputStream, AudioParameters params, 
AcquireResponse callback);

    interface AcquireResponse extends org.chromium.mojo.bindings.Callbacks.Callback2<org.chromium.mojo.system.SharedBufferHandle, org.chromium.mojo.system.UntypedHandle> { }


}
