
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/interfaces/audio_decoder.mojom
//

package org.chromium.media.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public interface AudioDecoder extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends AudioDecoder, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<AudioDecoder, AudioDecoder.Proxy> MANAGER = AudioDecoder_Internal.MANAGER;


    void construct(
org.chromium.mojo.bindings.AssociatedInterfaceNotSupported client);



    void initialize(
AudioDecoderConfig config, int cdmId, 
InitializeResponse callback);

    interface InitializeResponse extends org.chromium.mojo.bindings.Callbacks.Callback2<Boolean, Boolean> { }



    void setDataSource(
org.chromium.mojo.system.DataPipe.ConsumerHandle receivePipe);



    void decode(
DecoderBuffer buffer, 
DecodeResponse callback);

    interface DecodeResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }



    void reset(

ResetResponse callback);

    interface ResetResponse extends org.chromium.mojo.bindings.Callbacks.Callback0 { }


}
