
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/interfaces/media_types.mojom
//

package org.chromium.media.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public final class DecoderBuffer extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 64;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(64, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public org.chromium.mojo.common.mojom.TimeDelta timestamp;
    public org.chromium.mojo.common.mojom.TimeDelta duration;
    public boolean isEndOfStream;
    public int dataSize;
    public boolean isKeyFrame;
    public byte[] sideData;
    public DecryptConfig decryptConfig;
    public org.chromium.mojo.common.mojom.TimeDelta frontDiscard;
    public org.chromium.mojo.common.mojom.TimeDelta backDiscard;

    private DecoderBuffer(int version) {
        super(STRUCT_SIZE, version);
    }

    public DecoderBuffer() {
        this(0);
    }

    public static DecoderBuffer deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static DecoderBuffer deserialize(java.nio.ByteBuffer data) {
        if (data == null)
            return null;

        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static DecoderBuffer decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        DecoderBuffer result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            result = new DecoderBuffer(mainDataHeader.elementsOrVersion);
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, false);
                result.timestamp = org.chromium.mojo.common.mojom.TimeDelta.decode(decoder1);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(16, false);
                result.duration = org.chromium.mojo.common.mojom.TimeDelta.decode(decoder1);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                result.isEndOfStream = decoder0.readBoolean(24, 0);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                result.isKeyFrame = decoder0.readBoolean(24, 1);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                result.dataSize = decoder0.readInt(28);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                result.sideData = decoder0.readBytes(32, org.chromium.mojo.bindings.BindingsHelper.NOTHING_NULLABLE, org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(40, true);
                result.decryptConfig = DecryptConfig.decode(decoder1);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(48, false);
                result.frontDiscard = org.chromium.mojo.common.mojom.TimeDelta.decode(decoder1);
            }
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(56, false);
                result.backDiscard = org.chromium.mojo.common.mojom.TimeDelta.decode(decoder1);
            }
        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(timestamp, 8, false);
        
        encoder0.encode(duration, 16, false);
        
        encoder0.encode(isEndOfStream, 24, 0);
        
        encoder0.encode(isKeyFrame, 24, 1);
        
        encoder0.encode(dataSize, 28);
        
        encoder0.encode(sideData, 32, org.chromium.mojo.bindings.BindingsHelper.NOTHING_NULLABLE, org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
        
        encoder0.encode(decryptConfig, 40, true);
        
        encoder0.encode(frontDiscard, 48, false);
        
        encoder0.encode(backDiscard, 56, false);
    }

    /**
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(Object object) {
        if (object == this)
            return true;
        if (object == null)
            return false;
        if (getClass() != object.getClass())
            return false;
        DecoderBuffer other = (DecoderBuffer) object;
        if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.timestamp, other.timestamp))
            return false;
        if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.duration, other.duration))
            return false;
        if (this.isEndOfStream!= other.isEndOfStream)
            return false;
        if (this.dataSize!= other.dataSize)
            return false;
        if (this.isKeyFrame!= other.isKeyFrame)
            return false;
        if (!java.util.Arrays.equals(this.sideData, other.sideData))
            return false;
        if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.decryptConfig, other.decryptConfig))
            return false;
        if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.frontDiscard, other.frontDiscard))
            return false;
        if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.backDiscard, other.backDiscard))
            return false;
        return true;
    }

    /**
     * @see Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = prime + getClass().hashCode();
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(timestamp);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(duration);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(isEndOfStream);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(dataSize);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(isKeyFrame);
        result = prime * result + java.util.Arrays.hashCode(sideData);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(decryptConfig);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(frontDiscard);
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(backDiscard);
        return result;
    }
}