
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/interfaces/renderer.mojom
//

package org.chromium.media.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public interface RendererClient extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends RendererClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<RendererClient, RendererClient.Proxy> MANAGER = RendererClient_Internal.MANAGER;


    void onTimeUpdate(
org.chromium.mojo.common.mojom.TimeDelta time, org.chromium.mojo.common.mojom.TimeDelta maxTime, org.chromium.mojo.common.mojom.TimeTicks captureTime);



    void onBufferingStateChange(
int state);



    void onEnded(
);



    void onError(
);



    void onVideoNaturalSizeChange(
org.chromium.gfx.mojom.Size size);



    void onVideoOpacityChange(
boolean opaque);



    void onStatisticsUpdate(
PipelineStatistics stats);



    void onWaitingForDecryptionKey(
);



    void onDurationChange(
org.chromium.mojo.common.mojom.TimeDelta duration);


}
