
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     public/browser/navigation_controller.h

package org.chromium.content_public.browser.navigation_controller;

public class LoadURLType {
  public static final int DEFAULT = 0;
  public static final int BROWSER_INITIATED_HTTP_POST = 1;
  public static final int DATA = 2;
}
