
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/public/interfaces/bindings/pipe_control_messages.mojom
//

package org.chromium.mojo.bindings.pipecontrol;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public final class RunOrClosePipeInput extends org.chromium.mojo.bindings.Union {

    public static final class Tag {
        public static final int PeerAssociatedEndpointClosedEvent = 0;
    };

    private int mTag_ = -1;
    private PeerAssociatedEndpointClosedEvent mPeerAssociatedEndpointClosedEvent;

    public int which() {
      return mTag_;
    }

    public boolean isUnknown() {
      return mTag_ == -1;
    }

    // TODO(rockot): Fix the findbugs error and remove this suppression.
    // See http://crbug.com/570386.
    @SuppressFBWarnings("EI_EXPOSE_REP2")
    public void setPeerAssociatedEndpointClosedEvent(PeerAssociatedEndpointClosedEvent peerAssociatedEndpointClosedEvent) {
        mTag_ = Tag.PeerAssociatedEndpointClosedEvent;
        mPeerAssociatedEndpointClosedEvent = peerAssociatedEndpointClosedEvent;
    }

    // TODO(rockot): Fix the findbugs error and remove this suppression.
    // See http://crbug.com/570386.
    @SuppressFBWarnings("EI_EXPOSE_REP")
    public PeerAssociatedEndpointClosedEvent getPeerAssociatedEndpointClosedEvent() {
        assert mTag_ == Tag.PeerAssociatedEndpointClosedEvent;
        return mPeerAssociatedEndpointClosedEvent;
    }


    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder0, int offset) {
        encoder0.encode(org.chromium.mojo.bindings.BindingsHelper.UNION_SIZE, offset);
        encoder0.encode(mTag_, offset + 4);
        switch (mTag_) {
            case Tag.PeerAssociatedEndpointClosedEvent: {
                
                encoder0.encode(mPeerAssociatedEndpointClosedEvent, offset + 8, false);
                break;
            }
            default: {
                break;
            }
        }
    }

    public static RunOrClosePipeInput deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message).decoderForSerializedUnion(), 0);
    }

    public static final RunOrClosePipeInput decode(org.chromium.mojo.bindings.Decoder decoder0, int offset) {
        org.chromium.mojo.bindings.DataHeader dataHeader = decoder0.readDataHeaderForUnion(offset);
        if (dataHeader.size == 0) {
            return null;
        }
        RunOrClosePipeInput result = new RunOrClosePipeInput();
        switch (dataHeader.elementsOrVersion) {
            case Tag.PeerAssociatedEndpointClosedEvent: {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(offset + org.chromium.mojo.bindings.DataHeader.HEADER_SIZE, false);
                result.mPeerAssociatedEndpointClosedEvent = PeerAssociatedEndpointClosedEvent.decode(decoder1);
                result.mTag_ = Tag.PeerAssociatedEndpointClosedEvent;
                break;
            }
            default: {
                break;
            }
        }
        return result;
    }

    /**
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(Object object) {
        if (object == this)
            return true;
        if (object == null)
            return false;
        if (getClass() != object.getClass())
            return false;
        RunOrClosePipeInput other = (RunOrClosePipeInput) object;
        if (mTag_ != other.mTag_)
            return false;
        switch (mTag_) {
            case Tag.PeerAssociatedEndpointClosedEvent:
                return org.chromium.mojo.bindings.BindingsHelper.equals(mPeerAssociatedEndpointClosedEvent, other.mPeerAssociatedEndpointClosedEvent);
            default:
                break;
        }
        return false;
    }

    /**
     * @see Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = prime + getClass().hashCode();
        result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(mTag_);
        switch (mTag_) {
            case Tag.PeerAssociatedEndpointClosedEvent: {
                result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(mPeerAssociatedEndpointClosedEvent);
                break;
            }
            default: {
                break;
            }
        }
        return result;
    }
}