
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/offline_items_collection/core/offline_item.h

package org.chromium.components.offline_items_collection;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    OfflineItemProgressUnit.BYTES, OfflineItemProgressUnit.FILES, OfflineItemProgressUnit.PERCENTAGE
})
@Retention(RetentionPolicy.SOURCE)
public @interface OfflineItemProgressUnit {
  int BYTES = 0;
  int FILES = 1;
  int PERCENTAGE = 2;
}
