
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     bookmarks/common/android/bookmark_type.h

package org.chromium.components.bookmarks;

public class BookmarkType {
  public static final int NORMAL = 0;
  public static final int PARTNER = 1;
}
