
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     ax_enums.idl

package org.chromium.ui.accessibility;

public class AXTextStyle {
  public static final int text_style_bold = 1;
  public static final int text_style_italic = 2;
  public static final int text_style_underline = 4;
  public static final int text_style_line_through = 8;
}
