
// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_google_api_keys.py
// From
//     google_api_keys/google_api_keys.h

package org.chromium.chrome;

public class GoogleAPIKeys {
  public static final String GOOGLE_CLIENT_ID_REMOTING_HOST = "dummytoken";
  public static final String GOOGLE_CLIENT_ID_REMOTING_IDENTITY_API = "dummytoken";
  public static final String GOOGLE_API_KEY = "dummytoken";
  public static final String GOOGLE_CLIENT_ID_REMOTING = "dummytoken";
  public static final String GOOGLE_API_KEY_REMOTING = "dummytoken";
  public static final String GOOGLE_CLIENT_SECRET_REMOTING_HOST = "dummytoken";
  public static final String GOOGLE_CLIENT_ID_CLOUD_PRINT = "dummytoken";
  public static final String GOOGLE_CLIENT_SECRET_MAIN = "dummytoken";
  public static final String GOOGLE_CLIENT_ID_MAIN = "dummytoken";
  public static final String GOOGLE_API_KEY_PHYSICAL_WEB_TEST = "dummytoken";
  public static final String GOOGLE_CLIENT_SECRET_REMOTING = "dummytoken";
  public static final String GOOGLE_CLIENT_SECRET_CLOUD_PRINT = "dummytoken";
}
