
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/ui/sad_tab.cc

package org.chromium.chrome.browser.tab;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    SadTabEvent.DISPLAYED, SadTabEvent.BUTTON_CLICKED, SadTabEvent.HELP_LINK_CLICKED,
    SadTabEvent.MAX_SAD_TAB_EVENT
})
@Retention(RetentionPolicy.SOURCE)
public @interface SadTabEvent {
  int DISPLAYED = 0;
  int BUTTON_CLICKED = 1;
  int HELP_LINK_CLICKED = 2;
  int MAX_SAD_TAB_EVENT = 3;
}
