
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/accessibility/browser_accessibility_manager_android.h

package org.chromium.content.browser.accessibility;

public class ScrollDirection {
  public static final int FORWARD = 0;
  public static final int BACKWARD = 1;
  public static final int UP = 2;
  public static final int DOWN = 3;
  public static final int LEFT = 4;
  public static final int RIGHT = 5;
}
