
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     resources/resource_manager.h

package org.chromium.ui.resources;

public class AndroidResourceType {
  public static final int STATIC = 0;
  public static final int DYNAMIC = 1;
  public static final int DYNAMIC_BITMAP = 2;
  public static final int SYSTEM = 3;
  public static final int COUNT = 4;
  public static final int FIRST = 0;
  public static final int LAST = 3;
}
