
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/offline_pages/core/offline_store_types.h

package org.chromium.components.offlinepages;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ItemActionStatus.SUCCESS, ItemActionStatus.ALREADY_EXISTS, ItemActionStatus.NOT_FOUND,
    ItemActionStatus.STORE_ERROR
})
@Retention(RetentionPolicy.SOURCE)
public @interface ItemActionStatus {
  int SUCCESS = 0;
  int ALREADY_EXISTS = 1;
  int NOT_FOUND = 2;
  int STORE_ERROR = 3;
}
