
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/payments/core/journey_logger.h

package org.chromium.chrome.browser.payments;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    Event.INITIATED, Event.SHOWN, Event.PAY_CLICKED, Event.RECEIVED_INSTRUMENT_DETAILS,
    Event.SKIPPED_SHOW, Event.ENUM_MAX
})
@Retention(RetentionPolicy.SOURCE)
public @interface Event {
  int INITIATED = 0;
  int SHOWN = 1 << 0;
  int PAY_CLICKED = 1 << 1;
  int RECEIVED_INSTRUMENT_DETAILS = 1 << 2;
  int SKIPPED_SHOW = 1 << 3;
  int ENUM_MAX = 16;
}
