
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/payments/core/journey_logger.h

package org.chromium.chrome.browser.payments;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    Section.CONTACT_INFO, Section.CREDIT_CARDS, Section.SHIPPING_ADDRESS, Section.MAX
})
@Retention(RetentionPolicy.SOURCE)
public @interface Section {
  int CONTACT_INFO = 0;
  int CREDIT_CARDS = 1;
  int SHIPPING_ADDRESS = 2;
  int MAX = 3;
}
