
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/capture/video/android/photo_capabilities.h

package org.chromium.media;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    AndroidMeteringMode.NOT_SET, AndroidMeteringMode.NONE, AndroidMeteringMode.FIXED,
    AndroidMeteringMode.SINGLE_SHOT, AndroidMeteringMode.CONTINUOUS
})
@Retention(RetentionPolicy.SOURCE)
public @interface AndroidMeteringMode {
  int NOT_SET = 0;
  int NONE = 1;
  int FIXED = 2;
  int SINGLE_SHOT = 3;
  int CONTINUOUS = 4;
}
