
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/base/android/media_codec_direction.h

package org.chromium.media;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    MediaCodecDirection.DECODER, MediaCodecDirection.ENCODER
})
@Retention(RetentionPolicy.SOURCE)
public @interface MediaCodecDirection {
  int DECODER = 0;
  int ENCODER = 1;
}
