
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     memory/memory_pressure_listener.h

package org.chromium.base;

public class MemoryPressureLevel {
  public static final int NONE = -1;
  public static final int MODERATE = 0;
  public static final int CRITICAL = 2;
}
