
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/ntp_tiles/ntp_tile.h

package org.chromium.chrome.browser.ntp;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class NTPTileSource {
  @IntDef({
      TOP_SITES, SUGGESTIONS_SERVICE, POPULAR, WHITELIST
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface NTPTileSourceEnum {}
  /**
   * Tile comes from the personal top sites list, based on local history.
   */
  public static final int TOP_SITES = 0;
  /**
   * Tile comes from the suggestions service, based on synced history.
   */
  public static final int SUGGESTIONS_SERVICE = 1;
  /**
   * Tile is regionally popular.
   */
  public static final int POPULAR = 2;
  /**
   * Tile is on an custodian-managed whitelist.
   */
  public static final int WHITELIST = 3;
}
