
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     components/payments/mojom/payment_manifest_parser.mojom
//

package org.chromium.payments.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public interface PaymentManifestParser extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends PaymentManifestParser, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<PaymentManifestParser, PaymentManifestParser.Proxy> MANAGER = PaymentManifestParser_Internal.MANAGER;


    void parsePaymentMethodManifest(
String content, 
ParsePaymentMethodManifestResponse callback);

    interface ParsePaymentMethodManifestResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<org.chromium.url.mojom.Url[]> { }



    void parseWebAppManifest(
String content, 
ParseWebAppManifestResponse callback);

    interface ParseWebAppManifestResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<WebAppManifestSection[]> { }


}
