
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     android/library_loader/library_loader_hooks.h

package org.chromium.base.library_loader;

public class LibraryProcessType {
  public static final int PROCESS_UNINITIALIZED = 0;
  public static final int PROCESS_BROWSER = 1;
  public static final int PROCESS_CHILD = 2;
  public static final int PROCESS_WEBVIEW = 3;
}
