
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     ../base/touch/touch_device.h

package org.chromium.ui.base;

public class HoverType {
  public static final int NONE = 1 << 0;
  public static final int FIRST = NONE;
  public static final int ON_DEMAND = 1 << 1;
  public static final int HOVER = 1 << 2;
  public static final int LAST = HOVER;
}
