// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.chromium.components.invalidation;

@SuppressWarnings("hiding")
public interface SerializedInvalidation {

  public static final class Invalidation extends
      com.google.protobuf.nano.ExtendableMessageNano<Invalidation> {

    private static volatile Invalidation[] _emptyArray;
    public static Invalidation[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Invalidation[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string object_id = 1;
    public java.lang.String objectId;

    // optional int32 object_source = 2;
    public java.lang.Integer objectSource;

    // optional int64 version = 3;
    public java.lang.Long version;

    // optional string payload = 4;
    public java.lang.String payload;

    public Invalidation() {
      clear();
    }

    public Invalidation clear() {
      objectId = null;
      objectSource = null;
      version = null;
      payload = null;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.objectId != null) {
        output.writeString(1, this.objectId);
      }
      if (this.objectSource != null) {
        output.writeInt32(2, this.objectSource);
      }
      if (this.version != null) {
        output.writeInt64(3, this.version);
      }
      if (this.payload != null) {
        output.writeString(4, this.payload);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.objectId != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.objectId);
      }
      if (this.objectSource != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.objectSource);
      }
      if (this.version != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.version);
      }
      if (this.payload != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.payload);
      }
      return size;
    }

    @Override
    public Invalidation mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.objectId = input.readString();
            break;
          }
          case 16: {
            this.objectSource = input.readInt32();
            break;
          }
          case 24: {
            this.version = input.readInt64();
            break;
          }
          case 34: {
            this.payload = input.readString();
            break;
          }
        }
      }
    }

    public static Invalidation parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Invalidation(), data);
    }

    public static Invalidation parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Invalidation().mergeFrom(input);
    }
  }
}
