
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/ui/page_info/page_info.h

package org.chromium.chrome.browser.page_info;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PageInfoAction.PAGE_INFO_OPENED, PageInfoAction.PAGE_INFO_COOKIES_DIALOG_OPENED,
    PageInfoAction.PAGE_INFO_CHANGED_PERMISSION, PageInfoAction.PAGE_INFO_CERTIFICATE_DIALOG_OPENED,
    PageInfoAction.PAGE_INFO_CONNECTION_HELP_OPENED, PageInfoAction.PAGE_INFO_SITE_SETTINGS_OPENED,
    PageInfoAction.PAGE_INFO_SECURITY_DETAILS_OPENED, PageInfoAction.PAGE_INFO_COUNT
})
@Retention(RetentionPolicy.SOURCE)
public @interface PageInfoAction {
  int PAGE_INFO_OPENED = 0;
  /**
   * No longer used; indicated actions for the old version of Page Info that had a "Permissions" tab
   * and a "Connection" tab. PAGE_INFO_PERMISSIONS_TAB_SELECTED = 1,
   * PAGE_INFO_CONNECTION_TAB_SELECTED = 2, PAGE_INFO_CONNECTION_TAB_SHOWN_IMMEDIATELY = 3,
   */
  int PAGE_INFO_COOKIES_DIALOG_OPENED = 4;
  int PAGE_INFO_CHANGED_PERMISSION = 5;
  int PAGE_INFO_CERTIFICATE_DIALOG_OPENED = 6;
  /**
   * No longer used; indicated a UI viewer for SCTs. PAGE_INFO_TRANSPARENCY_VIEWER_OPENED = 7,
   */
  int PAGE_INFO_CONNECTION_HELP_OPENED = 8;
  int PAGE_INFO_SITE_SETTINGS_OPENED = 9;
  int PAGE_INFO_SECURITY_DETAILS_OPENED = 10;
  int PAGE_INFO_COUNT = 11;
}
