
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/common/browser_controls_state.h

package org.chromium.content_public.common;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    BrowserControlsState.SHOWN, BrowserControlsState.HIDDEN, BrowserControlsState.BOTH,
    BrowserControlsState.LAST
})
@Retention(RetentionPolicy.SOURCE)
public @interface BrowserControlsState {
  int SHOWN = 1;
  int HIDDEN = 2;
  int BOTH = 3;
  int LAST = BOTH;
}
