
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/common/console_message_level.h

package org.chromium.content_public.common;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    ConsoleMessageLevel.VERBOSE, ConsoleMessageLevel.INFO, ConsoleMessageLevel.WARNING,
    ConsoleMessageLevel.ERROR, ConsoleMessageLevel.LAST
})
@Retention(RetentionPolicy.SOURCE)
public @interface ConsoleMessageLevel {
  int VERBOSE = 0;
  int INFO = 1;
  int WARNING = 2;
  int ERROR = 3;
  int LAST = 3;
}
