
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../device/sensors/sensor_manager_android.h

package org.chromium.device.sensors;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    OrientationSensorType.NOT_AVAILABLE, OrientationSensorType.ROTATION_VECTOR,
    OrientationSensorType.ACCELEROMETER_MAGNETIC, OrientationSensorType.GAME_ROTATION_VECTOR,
    OrientationSensorType.ORIENTATION_SENSOR_MAX
})
@Retention(RetentionPolicy.SOURCE)
public @interface OrientationSensorType {
  int NOT_AVAILABLE = 0;
  int ROTATION_VECTOR = 1;
  int ACCELEROMETER_MAGNETIC = 2;
  int GAME_ROTATION_VECTOR = 3;
  int ORIENTATION_SENSOR_MAX = 4;
}
