
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/ntp_snippets/content_suggestions_service.cc

package org.chromium.chrome.browser.ntp.snippets;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    FaviconFetchResult.SUCCESS_CACHED, FaviconFetchResult.SUCCESS_FETCHED,
    FaviconFetchResult.FAILURE, FaviconFetchResult.COUNT
})
@Retention(RetentionPolicy.SOURCE)
public @interface FaviconFetchResult {
  int SUCCESS_CACHED = 0;
  int SUCCESS_FETCHED = 1;
  int FAILURE = 2;
  int COUNT = 3;
}
