
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     build/android/gyp/java_cpp_enum.py
// From
//     browser/android/gesture_event_type.h

package org.chromium.content.browser;

public class GestureEventType {
  public static final int SHOW_PRESS = 0;
  public static final int DOUBLE_TAP = 1;
  public static final int SINGLE_TAP_UP = 2;
  public static final int SINGLE_TAP_CONFIRMED = 3;
  public static final int SINGLE_TAP_UNCONFIRMED = 4;
  public static final int LONG_PRESS = 5;
  public static final int SCROLL_START = 6;
  public static final int SCROLL_BY = 7;
  public static final int SCROLL_END = 8;
  public static final int FLING_START = 9;
  public static final int FLING_CANCEL = 10;
  public static final int FLING_END = 11;
  public static final int PINCH_BEGIN = 12;
  public static final int PINCH_BY = 13;
  public static final int PINCH_END = 14;
  public static final int TAP_CANCEL = 15;
  public static final int LONG_TAP = 16;
  public static final int TAP_DOWN = 17;
}
