
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../third_party/WebKit/public/platform/WebDisplayMode.h

package org.chromium.blink_public.platform;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    WebDisplayMode.UNDEFINED, WebDisplayMode.BROWSER, WebDisplayMode.MINIMAL_UI,
    WebDisplayMode.STANDALONE, WebDisplayMode.FULLSCREEN, WebDisplayMode.LAST
})
@Retention(RetentionPolicy.SOURCE)
public @interface WebDisplayMode {
  int UNDEFINED = 0;
  int BROWSER = 1;
  int MINIMAL_UI = 2;
  int STANDALONE = 3;
  int FULLSCREEN = 4;
  int LAST = 4;
}
