
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/WebKit/public/platform/modules/payments/payment_request.mojom
//

package org.chromium.mojom.payments;

import org.chromium.base.annotations.SuppressFBWarnings;
import org.chromium.mojo.bindings.DeserializationException;


public interface PaymentRequestClient extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends PaymentRequestClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<PaymentRequestClient, PaymentRequestClient.Proxy> MANAGER = PaymentRequestClient_Internal.MANAGER;


    void onShippingAddressChange(
PaymentAddress address);



    void onShippingOptionChange(
String shippingOptionId);



    void onPaymentResponse(
PaymentResponse response);



    void onError(
int error);



    void onComplete(
);



    void onAbort(
boolean abortedSuccessfully);


}
