
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/ntp_tiles/tile_source.h

package org.chromium.chrome.browser.suggestions;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    TileSource.TOP_SITES, TileSource.SUGGESTIONS_SERVICE, TileSource.POPULAR, TileSource.WHITELIST,
    TileSource.HOMEPAGE, TileSource.LAST
})
@Retention(RetentionPolicy.SOURCE)
public @interface TileSource {
  /**
   * Tile comes from the personal top sites list, based on local history.
   */
  int TOP_SITES = 0;
  /**
   * Tile comes from the suggestions service, based on synced history.
   */
  int SUGGESTIONS_SERVICE = 1;
  /**
   * Tile is regionally popular.
   */
  int POPULAR = 2;
  /**
   * Tile is on a custodian-managed whitelist.
   */
  int WHITELIST = 3;
  /**
   * Tile containing the user-set home page is replacing the home page button.
   */
  int HOMEPAGE = 4;
  int LAST = 4;
}
